#!/usr/bin/env python3
"""Regenerate scripts/optima-metrics.json — the glyph widths build-deck.js measures with.

    python3 scripts/gen-font-metrics.py

Why this exists: build-deck.js has to know whether a lyric line fits on a slide,
and it has no browser and no font library. It used to guess with a character
count (55 chars = one line), which is a monospace assumption applied to Optima —
a proportional face. That estimate was wrong by up to 24% of the box, silently
wrapping hymn lines mid-phrase.

Summing per-glyph advances reproduces the browser's line width EXACTLY here
(0.00% error): Optima applies no kerning to this glyph set. So a small embedded
table buys real typographic measurement with no runtime dependency.

Re-run this only if templates/service-slides-template.html changes the lyric font
or its size.
"""

import json
from pathlib import Path

from PIL import ImageFont

FONT = "/System/Library/Fonts/Optima.ttc"
SIZE = 60  # the template's .lyric font-size; all other sizes scale linearly
OUT = Path(__file__).parent / "optima-metrics.json"

# ASCII, plus the punctuation hymn texts actually use (curly quotes, em/en dashes)
# and the accented letters that turn up in older hymnals.
CHARS = [chr(c) for c in range(32, 127)] + list(
    "’‘“”—–…·«»áàâäéèêëíìîïóòôöúùûüñçÁÀÂÄÉÈÊËÍÎÏÓÔÖÚÛÜÑÇ"
)


def main() -> None:
    font = ImageFont.truetype(FONT, SIZE, index=0)
    advances = {ch: round(font.getlength(ch), 2) for ch in CHARS}

    OUT.write_text(
        json.dumps(
            {
                "_comment": (
                    "Advance widths for Optima Regular at font-size 60px, in px. "
                    "GENERATED by scripts/gen-font-metrics.py — do not hand-edit. "
                    "Optima applies no kerning to these glyphs, so summing advances "
                    "reproduces the browser's line width exactly. Scale linearly for "
                    "other sizes."
                ),
                "font": "Optima Regular",
                "size": SIZE,
                # For any glyph not in the table (rare), assume an average lowercase
                # letter. Slightly generous is fine; slightly narrow would overflow.
                "fallback": round(sum(advances[c] for c in "abcdefghijklmnopqrstuvwxyz") / 26, 2),
                "advances": advances,
            },
            indent=1,
            ensure_ascii=False,
        )
        + "\n"
    )
    print(f"wrote {OUT} — {len(advances)} glyphs")


if __name__ == "__main__":
    main()
